[system]
compatible=obake
bootloader=efi
mountprefix=/mnt/rauc

[keyring]
path=/etc/rauc/ca.cert.pem

[slot.rootfs.0]
device=/dev/disk/by-partlabel/OBKA_ROOT_A
type=ext4
bootname=A

[slot.rootfs.1]
device=/dev/disk/by-partlabel/OBKA_ROOT_B
type=ext4
bootname=B
